# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: required

r_packages:
  - covr

## After success update the code coverage
after_success:
 - Rscript -e 'covr::codecov()'
 
## Email notification if the package pass status changes
notifications:
  email:
    recipients:
      - robboy@ceh.ac.uk
    on_success: change
    on_failure: change

# Warnings dont fail build
warnings_are_errors: false

## Set up the matrix of different runs
env:
  matrix:
    - r: release
      not_cran: true
      r_check_args: "--no-manual"
    - r: release
      not_cran: false
      r_check_args: "--no-manual --as--cran"
    - r: devel
      not_cran: true
      r_check_args: "--no-manual"
    - r: devel
      not_cran: false
      r_check_args: "--no-manual --as--cran"